name: CI

on:
  push:
    branches: ["*.*.x"]
  pull_request:
    branches: ["*.*.x"]

env:
  CARGO_TERM_COLOR: always

jobs:
  lint:
    name: Run clippy
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
        with:
          shared-key: debug
      - run: cargo clippy -- -Dwarnings

  build:
    name: Build and upload an artifact for ${{ matrix.name }}
    uses: ./.github/workflows/build.yml
    strategy:
      matrix:
        os:
          - windows-latest
          - macos-14
          - macos-latest
          - ubuntu-latest
        include:
          - os: windows-latest
            name: Windows
            triplet: x86_64-pc-windows-msvc
          - os: macos-14
            name: MacOS Silicon
            triplet: aarch64-apple-darwin
          - os: macos-latest
            name: MacOS Intel
            triplet: x86_64-apple-darwin
          - os: ubuntu-latest
            name: Linux
            triplet: x86_64-unknown-linux-gnu
    with:
      os: ${{ matrix.os }}
      triplet: ${{ matrix.triplet }}
