name: Release

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

env:
  CARGO_INCREMENTAL: 0 # Incremental not supported by our caching
  CARGO_TERM_COLOR: always # GH action logs supports terminal colors
  CARGO_REGISTRIES_CRATES_IO_PROTOCOL: sparse # New format as of 2023-03-09

jobs:
  prepare:
    name: Build and upload a release artifact for ${{ matrix.name }}
    uses: ./.github/workflows/build.yml
    strategy:
      matrix:
        os:
          - windows-latest
          - macos-14
          - macos-latest
          - ubuntu-latest
        include:
          - os: windows-latest
            name: Windows
            triplet: x86_64-pc-windows-msvc
          - os: macos-14
            name: MacOS Silicon
            triplet: aarch64-apple-darwin
          - os: macos-latest
            name: MacOS Intel
            triplet: x86_64-apple-darwin
          - os: ubuntu-latest
            name: Linux
            triplet: x86_64-unknown-linux-gnu
    with:
      os: ${{ matrix.os }}
      triplet: ${{ matrix.triplet }}
  publish:
    name: Release artifacts
    needs: prepare
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          path: binaries
          merge-multiple: true
      - env:
          GH_TOKEN: ${{ github.token }}
        run: gh release create ${{ github.ref_name }} --generate-notes ./binaries/*
